spring:
  application:
    name: my-eureka-server

server:
  port: 8084

eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: replica
  application:
    name: my-eureka-server   # ==> This is Service-Id
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
---
